MAILGUN_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
SANDBOX_URL = 'sandboxXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mailgun.org'
SENDER_EMAIL = 'test@'+'sandboxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mailgun.org'
RECIPIENT_EMAIL = 'XXXXXXXXXXXXXXXX@gmail.com'
